[package]
name = "gkosgrep"
version = "0.1.0"
authors = ["Daniel Hilst Selli <danielhilst@gmail.com>"]
edition = "2018"
license = "Apache 2.0"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/dhilst/gkosgrep"
homepage = "https://github.com/dhilst/gkosgrep"
keywords = ["grep"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "*"
regex = "1"
content_inspector = "*"
glob = "*"
