[package]
name = "rgrep"
version = "0.1.0"
authors = ["Daniel Hilst Selli <daniel@versatushpc.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "*"
regex = "1"
content_inspector = "*"
glob = "*"
